package app

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"k8s.io/client-go/dynamic"

	"github.com/caseyrobb/kubescrub/internal/apply"
	"github.com/caseyrobb/kubescrub/internal/kube"
	"github.com/caseyrobb/kubescrub/internal/policy"
)

// validateApply checks apply-mode safety gates before execution.
// When realApply && yes it returns errors for guard violations.
// In dry-run mode it writes warnings to stderr and returns nil.
func validateApply(plan *apply.Plan, realApply, yes bool,
	maxPlanAge time.Duration, context string,
) error {
	// --apply without --yes is always an error.
	if realApply && !yes {
		return fmt.Errorf("--apply requires --yes to perform real deletions")
	}

	isReal := realApply && yes
	var errs []string

	// Guard: plan age.
	planTime, err := time.Parse(time.RFC3339, plan.GeneratedAt)
	if err != nil {
		return fmt.Errorf("parse plan generatedAt: %w", err)
	}
	age := time.Since(planTime)
	if age > maxPlanAge {
		msg := fmt.Sprintf("plan is %s old (max-plan-age: %s)",
			age.Round(time.Second), maxPlanAge)
		if isReal {
			errs = append(errs, msg)
		} else {
			fmt.Fprintf(os.Stderr, "WARNING: %s\n", msg)
		}
	}

	// Guard: context mismatch.
	if context != "" && plan.Cluster != "" && context != plan.Cluster {
		msg := fmt.Sprintf("context %q does not match plan.cluster %q (scan was run on %q)",
			context, plan.Cluster, plan.Cluster)
		if isReal {
			errs = append(errs, msg)
		} else {
			fmt.Fprintf(os.Stderr, "WARNING: %s\n", msg)
		}
	}

	if len(errs) > 0 {
		// Combine all violations.
		return fmt.Errorf("apply refused: %s", strings.Join(errs, "; "))
	}

	return nil
}

func newApplyCmd(policyPath, kubeconfig, context *string) *cobra.Command {
	var planPath string
	var realApply bool
	var yes bool
	var checks string
	var reasons string
	var namespace string
	var maxPlanAge time.Duration

	cmd := &cobra.Command{
		Use:   "apply",
		Short: "Apply deletion plan from a scan report",
		Long: `Apply a deletion plan generated by kubescrub scan.

The apply command reads a JSON report file and deletes resources that are
safe to delete. Safety gates include:

  - SuggestedAction must be "delete"
  - SafeToApply must be true
  - Kind must not be in the hard-block list (CRD, Role, ClusterRole, etc.)
  - The live object must have the allow-delete annotation
  - Namespace must not be excluded
  - Plan must not be older than --max-plan-age (default 24h)
  - --context must match plan.cluster (when plan.cluster is non-empty)

By default, apply runs in dry-run mode. Use --apply --yes to perform
real deletions.

Examples:
  kubescrub apply --plan report.json                          # dry-run
  kubescrub apply --plan report.json --apply                  # error: --yes required
  kubescrub apply --plan report.json --apply --yes            # real delete
  kubescrub apply --plan report.json --checks workload,pvc    # only workload+PVC
  kubescrub apply --plan report.json --reason completed-job   # only completed-job
  kubescrub apply --plan report.json --namespace kubescrub-messy  # only one namespace
  kubescrub apply --plan report.json --max-plan-age 1h        # refuse stale plans
  kubescrub apply --plan report.json --context kind-dev       # require context match
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if planPath == "" {
				return fmt.Errorf("--plan is required")
			}

			// Validate mode: --apply without --yes is an error.
			if realApply && !yes {
				return fmt.Errorf("--apply requires --yes to perform real deletions")
			}

			// Determine mode.
			isRealApply := realApply && yes

			if isRealApply {
				fmt.Fprintln(os.Stderr, "⚠  WARNING: real deletion mode enabled. Press Ctrl+C to abort.")
			} else {
				fmt.Fprintln(os.Stderr, "ℹ  Dry-run mode: no resources will be deleted.")
			}

			// Load policy.
			p, err := policy.Load(*policyPath)
			if err != nil {
				return fmt.Errorf("load policy: %w", err)
			}

			// Load plan (returns both Plan and PlanResult).
			plan, planResult, err := apply.Load(planPath, *p)
			if err != nil {
				return fmt.Errorf("load plan: %w", err)
			}

			// Validate apply-mode safety gates (age, context).
			if err := validateApply(plan, realApply, yes, maxPlanAge, *context); err != nil {
				return err
			}

			// Post-load filtering (checks, reasons, namespace).
			var checkList []string
			if checks != "" {
				checkList = strings.Split(checks, ",")
			}
			var reasonList []string
			if reasons != "" {
				reasonList = strings.Split(reasons, ",")
			}
			planResult = apply.FilterCandidates(planResult, plan, apply.ApplyFilters{
				Checks:    checkList,
				Reasons:   reasonList,
				Namespace: namespace,
			})

			if len(planResult.Candidates) == 0 {
				fmt.Fprintf(os.Stderr, "No findings eligible for apply. %d skipped:\n",
					len(planResult.SkippedReasons))
				for _, s := range planResult.SkippedReasons {
					fmt.Fprintf(os.Stderr, "  - %s: %s\n", s.FindingID, s.Reason)
				}
				return nil
			}

			fmt.Fprintf(os.Stderr, "Plan: %d candidates for apply, %d skipped\n",
				len(planResult.Candidates), len(planResult.SkippedReasons))

			// Resolve kubeconfig path and build client.
			kubeconfigPath := kube.ResolveKubeconfigPath(*kubeconfig)
			k8sClient, err := kube.NewClient(kubeconfigPath, *context)
			if err != nil {
				return fmt.Errorf("build kubernetes client: %w", err)
			}

			var dyn dynamic.Interface = k8sClient.Dynamic

			// Execute.
			ctx := cmd.Context()
			dryRun := !isRealApply
			result, err := apply.Execute(ctx, dyn, planResult.Candidates, p, dryRun)
			if err != nil {
				return fmt.Errorf("execute apply: %w", err)
			}

			// Print summary.
			output := apply.FormatResult(result)
			fmt.Println(output)

			// Exit with error if dry-run failures occurred.
			if len(result.DryRunFail) > 0 {
				return fmt.Errorf("%d dry-run failures", len(result.DryRunFail))
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&planPath, "plan", "", "Path to scan report JSON file (required)")
	cmd.Flags().BoolVar(&realApply, "apply", false, "Enable real deletion (requires --yes)")
	cmd.Flags().BoolVar(&yes, "yes", false, "Acknowledge real deletion (required with --apply)")
	cmd.Flags().StringVar(&checks, "checks", "", "Comma-separated list of check names to include (default all)")
	cmd.Flags().StringVar(&reasons, "reason", "", "Comma-separated list of finding reasons to include (default all)")
	cmd.Flags().StringVar(&namespace, "namespace", "", "Only include findings in this exact namespace (cluster-scoped kept)")
	cmd.Flags().DurationVar(&maxPlanAge, "max-plan-age", 24*time.Hour, "Maximum age of the scan plan (default 24h)")

	cmd.MarkFlagRequired("plan")

	return cmd
}
